name: ci

on: 
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17.0.4'
      - name: Build
        run: >
          mvn clean install
          test -Dmaven.test.failure.ignore=true
          site -DgenerateReports=false
          surefire-report:report
        working-directory: Sample
      - name: Upload package
        if: always()
        uses: actions/upload-artifact@v1
        with: 
          name: package
          path: Sample/target/sample-1.0.0-SNAPSHOT.jar
      - name: Upload test resuls
        if: always()
        uses: actions/upload-artifact@v1
        with: 
          name: test-results
          path: Sample/target/surefire-reports
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "Sample/target/sample-1.0.0-SNAPSHOT.jar"
          target: "Sample/docker/"
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build, push
        uses: docker/build-push-action@v2
        with:
          context: docker/
          push: true
          tags: mortarco/experiment:latest
      - name: Generate sbom
        uses: anchore/sbom-action@v0.14.1
        with:
          image: mortarco/experiment:latest
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
      - name: Scan vulnerability
        uses: anchore/scan-action@v3
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
